### ISSUE TITLE
call of duty modern warfare

### ISSUE THREAD

**Issue by Lightlightingstorm** [microsoft/vsmarketplace#845]
Type: <b>Performance Issue</b>

Respitory

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.26040
Modes:

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vsmarketplace/issues/842
- [ ] https://github.com/microsoft/vsmarketplace/issues/834
- [ ] https://github.com/microsoft/vsmarketplace/issues/712
- [ ] https://github.com/microsoft/vsmarketplace/issues/844
- [ ] https://github.com/microsoft/vsmarketplace/issues/838
- [ ] https://github.com/microsoft/vsmarketplace/issues/843
- [ ] https://github.com/microsoft/vsmarketplace/issues/841
- [ ] https://github.com/microsoft/vsmarketplace/issues/835
- [ ] https://github.com/microsoft/vsmarketplace/issues/840
- [ ] https://github.com/microsoft/vsmarketplace/issues/836
- [ ] https://github.com/microsoft/vsmarketplace/issues/839
- [ ] https://github.com/microsoft/vsmarketplace/issues/619
```

**Comment by Lightlightingstorm** [comment]
hi

**Comment by madhurivadaligithub** [comment]
Hi @Lightlightingstorm 

Thanks for reaching out to the VS Marketplace Team. Could you please share more details about your concern to address it better.

-VS Marketplace Team
